export const loginControl = {
  userNameField: {
    value: '',
    key: 'userName',
    label: 'User Name',
    requiredErrMsg: 'userName is Required',
    patternErrMsg: 'userName is not valid',
    inputType: 'text',
    displayIcon: true,
    iconName: 'person',
  },
  passwordField: {
    value: '',
    key: 'password',
    label: 'Password',
    requiredErrMsg: 'Password is Required',
    patternErrMsg: 'Password is not valid',
    inputType: 'password',
    displayIcon: true,
    iconName: 'visibility',
  },
  checkboxField: {
    value: '',
    key: 'checkbox',
    label: 'Remember Me',
    inputType: 'text',
  },
  CheckboxItem: {
    value: '',
    key: 'checkbox',
    label: 'Is Active',
    requiredErrMsg: 'checkbox is Required',
    inputType: 'text',
  },
};
